name: CorpseImmortal
version: 0.0.1
main: ml.zer0dasho.corpseimmortal.CorpseImmortal

api-version: 1.18

depend: [Citizens]

commands:
    corpse:
        permission: corpseimmortal.corpse

permissions:
    corpseimmortal.corpse:
        default: op
